version: '3'  # Bisa dihapus jika menggunakan Docker Compose v2
services:
  laravel-customer-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    environment:
      - APP_ENV=local
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel_customer_api
      - DB_USERNAME=root
      - DB_PASSWORD=root
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_customer_api
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
volumes:
  dbdata:
